version: 0.2

env:
  variables:
    CYPRESS_RECORD_KEY: "your-cypress-record-key" # Optional, for Cypress Dashboard integration
    S3_BUCKET: "home-serve-build-reports-101"     # Your S3 bucket name
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g nx
      - npm ci --force
  pre_build:
    commands:
      - echo "Checking out the feature branch..."
      # - git fetch origin $FEATURE_BRANCH
      # - git checkout $FEATURE_BRANCH
      # - git reset --hard
      # echo "Static list of apps: dashboard, login"
      - export APPS="dashboard login"
  build:
    commands:
      - if [ -z "$APPS" ]; then echo "No affected apps. Skipping tests."; exit 0; fi
      - echo "Running unit tests for affected Nx apps..."
      - |
        for app in $APPS; do
          echo "Running unit tests for $app..."
          nx test $app --coverage --output-file coverage-summary.json || exit 1
          mkdir -p dist/reports/$app/unit-tests
          mv coverage/apps/$app/* dist/reports/$app/unit-tests/
        done
      - echo "Unit tests completed."
      - echo "Running Cypress E2E tests for affected apps..."
      - |
        for app in $APPS; do
          echo "Running E2E tests for $app..."
          nx e2e ${app}-e2e || exit 1
          mkdir -p dist/reports/$app/e2e
          cp -r cypress/screenshots dist/reports/$app/e2e/screenshots || echo "No screenshots to copy."
          cp -r cypress/videos dist/reports/$app/e2e/videos || echo "No videos to copy."
          cp -r cypress/reports/* dist/reports/$app/e2e/
        done
      - echo "Cypress E2E tests completed."
  # post_build:
#     commands:
#       - echo "Uploading reports to S3..."
#       - aws s3 cp dist/reports/ s3://$S3_BUCKET/$BUILD_FOLDER/unit-tests/ --recursive --exclude "*" --include "*unit-tests/*"
#       - aws s3 cp dist/reports/ s3://$S3_BUCKET/$BUILD_FOLDER/e2e/ --recursive --exclude "*" --include "*e2e/*"
#       - echo "Reports uploaded to S3: $S3_BUCKET/$BUILD_FOLDER"

# artifacts:
#   files:
#     - dist/build-reports.zip
#   base-directory: dist
#   discard-paths: no
