AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC, private subnets, and restrict access to an S3 static website using a VPC Endpoint and VPN.

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to host the static website.
    Default: my-cool-reports-2019
  VPNIpRanges:
    Type: CommaDelimitedList
    Default: 172.16.255.1/32
    Description: List of IP ranges (CIDR blocks) used by the company VPN (e.g., 203.0.113.0/24).
  CidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: S3Vpc

  # Private Subnet 1
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']

  # Private Subnet 2
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [1, !GetAZs '']

  # S3 Bucket for Static Website Hosting
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # Bucket Policy to Restrict Access to VPC Endpoint and VPN IP Ranges
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccessFromVPCAndVPN
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
            Condition:
              StringEquals:
                aws:SourceVpce: !Ref S3VpcEndpoint
              IpAddress:
                aws:SourceIp: !Ref VPNIpRanges

  # VPC Endpoint for S3
  S3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VPC
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable1
        - !Ref PrivateRouteTable2

  # Route Table for Private Subnet 1
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  # Route Table for Private Subnet 2
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

Outputs:
  VPCId:
    Description: The ID of the created VPC.
    Value: !Ref VPC

  S3WebsiteURL:
    Description: The URL of the S3 static website.
    Value: !Sub 'http://${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com'

  VpcEndpointId:
    Description: The ID of the S3 VPC Endpoint.
    Value: !Ref S3VpcEndpoint
